name: Deploy my page
on:
  push:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-run-tests:
    name: Deploy my page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: nodejs setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        uses: jaid/action-npm-install@v1.2.1
      - run: |
          npm install
          npm build

      - name: Save page
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build-run-tests

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
